language: python
matrix:
  include:
    - python: "3.4.2"
      env: TARGET=test
    - python: "3.4.4"
      env: TARGET=test
    - env: TARGET=beefore
install:
  - "pip install ."
  - "ant java"
script:
  - "python setup.py $TARGET"
